import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vite";
import { compression } from "vite-plugin-compression2";
import { VitePWA } from "vite-plugin-pwa";
import svgr from "vite-plugin-svgr";

// Rasterize the handcrafted og:image SVGs to PNG at build time.
// Messengers (Facebook, LinkedIn, iMessage, WhatsApp) require raster og:image.
// Sources live in src/assets/og; outputs land in public/ and are gitignored.
function rasterizeOG(): Plugin {
  const here = dirname(fileURLToPath(import.meta.url));
  const srcDir = resolve(here, "src/assets/og");
  const outDir = resolve(here, "public");
  const fontFile = resolve(srcDir, "Lexend.ttf");
  const variants = ["og-image", "og-invite"] as const;

  let done = false;
  return {
    name: "rasterize-og",
    async buildStart() {
      if (done) return;
      const { Resvg } = await import("@resvg/resvg-js");
      for (const name of variants) {
        const template = await readFile(resolve(srcDir, `${name}.svg`), "utf8");
        const resvg = new Resvg(template, { font: { fontFiles: [fontFile] } });
        for (const href of resvg.imagesToResolve()) {
          resvg.resolveImage(href, await readFile(resolve(srcDir, href)));
        }
        const png = resvg.render().asPng();
        await writeFile(resolve(outDir, `${name}.png`), png);
      }
      done = true;
    },
  };
}

export default defineConfig({
  plugins: [
    tanstackRouter({ target: "react", autoCodeSplitting: true }),
    react({
      babel: {
        plugins: [["babel-plugin-react-compiler", {}]],
      },
    }),
    svgr(),
    tailwindcss(),
    rasterizeOG(),
    compression({ algorithm: "gzip" }),
    compression({ algorithm: "brotliCompress" }),
    VitePWA({
      registerType: "autoUpdate",
      workbox: {
        globPatterns: ["**/*.{js,css,html}"],
        // env-config.js is generated by the server at runtime — never bundle
        // it. Precaching would freeze build-time defaults forever after the
        // SW installs. (Nothing under that name actually lands in dist/, but
        // an explicit ignore guards against a future accidental stub.)
        globIgnores: ["env-config.js"],
        // /p/:token is a server-handled bootstrap route — it sets the session
        // cookie on the response. If the SW navigation fallback intercepts
        // and serves cached index.html, the cookie never gets set. Force /p/*
        // to always hit the network.
        navigateFallbackDenylist: [/^\/p\//],
      },
      manifest: {
        name: "Spreadsheet",
        short_name: "Spreadsheet",
        description: "A yes/no/maybe list for couples and groups. Find the overlap.",
        theme_color: "#d08058",
        background_color: "#fdf9f5",
        display: "standalone",
        icons: [
          { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      // tRPC subscriptions over WebSocket — must come before /api so the more
      // specific path matches first.
      "/api/trpc-ws": {
        target: "ws://localhost:8080",
        ws: true,
      },
      "/api": {
        target: "http://localhost:8080",
        configure: (proxy) => {
          // Return 503 instead of spamming console when backend is restarting
          proxy.on("error", (_err, _req, res) => {
            if ("writeHead" in res) {
              res.writeHead(503, { "Content-Type": "application/json" });
              res.end(JSON.stringify({ error: "Backend unavailable" }));
            }
          });
        },
      },
    },
  },
});
