// All UI text in one place — ready for i18n later.
export const UI = {
  appName: "Spreadsheet",
  tagline: "Discover what you're both into",
  landing: {
    description:
      "A yes/no/maybe list for you and your partner. Rate activities privately, then see only the things you both want to try.",
    getStarted: "Get started",
  },
  createGroup: {
    title: "Create your group",
    nameLabel: "Your name",
    namePlaceholder: "Enter your name",
    anatomyLabel: "Your body",
    encryptedLabel: "End-to-end encryption",
    encryptedDescription: "Your answers are encrypted before leaving your device. Not even the server can read them.",
    create: "Create group",
  },
  intro: {
    title: "Here's how it works",
    steps: [
      "You'll see activities one at a time",
      "Rate each one honestly — there are no wrong answers",
      "Only matches are revealed — if either of you says no, it stays private",
      "Take your time. You can pause and come back anytime.",
    ],
    start: "Let's go",
    answersTitle: "Your answers",
    answers: {
      yes: ["Yes", "I want this"],
      willing: ["If partner wants", "I'm open to it if you are"],
      maybe: ["Maybe", "Not sure yet, open to talking about it"],
      fantasy: ["Fantasy only", "Fun to think about, not ready to try"],
      no: ["No", "Not for me — your partner won't see this"],
    } as Record<string, [string, string]>,
    timingTitle: "Timing",
    timing: {
      now: ["Now", "I'd like to try this soon"],
      later: ["Later", "Interested, but not right now"],
    } as Record<string, [string, string]>,
    tierTitle: "How many questions?",
    tiers: {
      1: { label: "Essentials", description: "The stuff most couples should talk about" },
      2: { label: "Common", description: "Broadly recognized practices and preferences" },
      3: { label: "Adventurous", description: "Niche but mainstream-aware kinks and dynamics" },
      4: { label: "Edge", description: "Higher-risk activities that need expertise" },
    } as Record<number, { label: string; description: string }>,
  },
  question: {
    yes: "Yes",
    willing: "If partner wants",
    maybe: "Maybe",
    fantasy: "Fantasy only",
    no: "No",
    whatsThis: "What's this?",
    when: "When?",
    now: "Now",
    later: "Later",
    back: "Back",
    skip: "Skip",
    sync: "Sync",
    syncing: "Syncing...",
    synced: "Synced",
    offline: "Offline",
    unsynced: (n: number) => `${n} unsynced`,
  },
  review: {
    title: "Review your answers",
    done: "I'm done",
    answered: (n: number, total: number) => `${n} of ${total} answered`,
  },
  group: {
    title: "Invite your partner",
    titleReady: "Your group",
    copyLink: "Copy link",
    copied: "Copied!",
    addPerson: "Add person",
    everyoneAdded: "Everyone is added",
    startFilling: "Start filling out",
    continueFilling: "Continue",
    viewAnswers: "View my answers",
    members: "Members",
  },
} as const;
