/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteRouteImport } from './routes/p/$token/route'
import { Route as PTokenWaitingRouteImport } from './routes/p/$token/waiting'
import { Route as PTokenSummaryRouteImport } from './routes/p/$token/summary'
import { Route as PTokenSetupRouteImport } from './routes/p/$token/setup'
import { Route as PTokenReviewRouteImport } from './routes/p/$token/review'
import { Route as PTokenResultsRouteImport } from './routes/p/$token/results'
import { Route as PTokenQuestionsRouteImport } from './routes/p/$token/questions'
import { Route as PTokenPendingRouteImport } from './routes/p/$token/pending'
import { Route as PTokenIntroRouteImport } from './routes/p/$token/intro'
import { Route as PTokenGroupRouteImport } from './routes/p/$token/group'
import { Route as PTokenAnatomyRouteImport } from './routes/p/$token/anatomy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRouteRoute = PTokenRouteRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenWaitingRoute = PTokenWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenSummaryRoute = PTokenSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenSetupRoute = PTokenSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenReviewRoute = PTokenReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenResultsRoute = PTokenResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenQuestionsRoute = PTokenQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenPendingRoute = PTokenPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenIntroRoute = PTokenIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenGroupRoute = PTokenGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => PTokenRouteRoute,
} as any)
const PTokenAnatomyRoute = PTokenAnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => PTokenRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRouteRouteWithChildren
  '/p/$token/anatomy': typeof PTokenAnatomyRoute
  '/p/$token/group': typeof PTokenGroupRoute
  '/p/$token/intro': typeof PTokenIntroRoute
  '/p/$token/pending': typeof PTokenPendingRoute
  '/p/$token/questions': typeof PTokenQuestionsRoute
  '/p/$token/results': typeof PTokenResultsRoute
  '/p/$token/review': typeof PTokenReviewRoute
  '/p/$token/setup': typeof PTokenSetupRoute
  '/p/$token/summary': typeof PTokenSummaryRoute
  '/p/$token/waiting': typeof PTokenWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRouteRouteWithChildren
  '/p/$token/anatomy': typeof PTokenAnatomyRoute
  '/p/$token/group': typeof PTokenGroupRoute
  '/p/$token/intro': typeof PTokenIntroRoute
  '/p/$token/pending': typeof PTokenPendingRoute
  '/p/$token/questions': typeof PTokenQuestionsRoute
  '/p/$token/results': typeof PTokenResultsRoute
  '/p/$token/review': typeof PTokenReviewRoute
  '/p/$token/setup': typeof PTokenSetupRoute
  '/p/$token/summary': typeof PTokenSummaryRoute
  '/p/$token/waiting': typeof PTokenWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRouteRouteWithChildren
  '/p/$token/anatomy': typeof PTokenAnatomyRoute
  '/p/$token/group': typeof PTokenGroupRoute
  '/p/$token/intro': typeof PTokenIntroRoute
  '/p/$token/pending': typeof PTokenPendingRoute
  '/p/$token/questions': typeof PTokenQuestionsRoute
  '/p/$token/results': typeof PTokenResultsRoute
  '/p/$token/review': typeof PTokenReviewRoute
  '/p/$token/setup': typeof PTokenSetupRoute
  '/p/$token/summary': typeof PTokenSummaryRoute
  '/p/$token/waiting': typeof PTokenWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$token'
    | '/p/$token/anatomy'
    | '/p/$token/group'
    | '/p/$token/intro'
    | '/p/$token/pending'
    | '/p/$token/questions'
    | '/p/$token/results'
    | '/p/$token/review'
    | '/p/$token/setup'
    | '/p/$token/summary'
    | '/p/$token/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$token'
    | '/p/$token/anatomy'
    | '/p/$token/group'
    | '/p/$token/intro'
    | '/p/$token/pending'
    | '/p/$token/questions'
    | '/p/$token/results'
    | '/p/$token/review'
    | '/p/$token/setup'
    | '/p/$token/summary'
    | '/p/$token/waiting'
  id:
    | '__root__'
    | '/'
    | '/p/$token'
    | '/p/$token/anatomy'
    | '/p/$token/group'
    | '/p/$token/intro'
    | '/p/$token/pending'
    | '/p/$token/questions'
    | '/p/$token/results'
    | '/p/$token/review'
    | '/p/$token/setup'
    | '/p/$token/summary'
    | '/p/$token/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PTokenRouteRoute: typeof PTokenRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token/waiting': {
      id: '/p/$token/waiting'
      path: '/waiting'
      fullPath: '/p/$token/waiting'
      preLoaderRoute: typeof PTokenWaitingRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/summary': {
      id: '/p/$token/summary'
      path: '/summary'
      fullPath: '/p/$token/summary'
      preLoaderRoute: typeof PTokenSummaryRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/setup': {
      id: '/p/$token/setup'
      path: '/setup'
      fullPath: '/p/$token/setup'
      preLoaderRoute: typeof PTokenSetupRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/review': {
      id: '/p/$token/review'
      path: '/review'
      fullPath: '/p/$token/review'
      preLoaderRoute: typeof PTokenReviewRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/results': {
      id: '/p/$token/results'
      path: '/results'
      fullPath: '/p/$token/results'
      preLoaderRoute: typeof PTokenResultsRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/questions': {
      id: '/p/$token/questions'
      path: '/questions'
      fullPath: '/p/$token/questions'
      preLoaderRoute: typeof PTokenQuestionsRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/pending': {
      id: '/p/$token/pending'
      path: '/pending'
      fullPath: '/p/$token/pending'
      preLoaderRoute: typeof PTokenPendingRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/intro': {
      id: '/p/$token/intro'
      path: '/intro'
      fullPath: '/p/$token/intro'
      preLoaderRoute: typeof PTokenIntroRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/group': {
      id: '/p/$token/group'
      path: '/group'
      fullPath: '/p/$token/group'
      preLoaderRoute: typeof PTokenGroupRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
    '/p/$token/anatomy': {
      id: '/p/$token/anatomy'
      path: '/anatomy'
      fullPath: '/p/$token/anatomy'
      preLoaderRoute: typeof PTokenAnatomyRouteImport
      parentRoute: typeof PTokenRouteRoute
    }
  }
}

interface PTokenRouteRouteChildren {
  PTokenAnatomyRoute: typeof PTokenAnatomyRoute
  PTokenGroupRoute: typeof PTokenGroupRoute
  PTokenIntroRoute: typeof PTokenIntroRoute
  PTokenPendingRoute: typeof PTokenPendingRoute
  PTokenQuestionsRoute: typeof PTokenQuestionsRoute
  PTokenResultsRoute: typeof PTokenResultsRoute
  PTokenReviewRoute: typeof PTokenReviewRoute
  PTokenSetupRoute: typeof PTokenSetupRoute
  PTokenSummaryRoute: typeof PTokenSummaryRoute
  PTokenWaitingRoute: typeof PTokenWaitingRoute
}

const PTokenRouteRouteChildren: PTokenRouteRouteChildren = {
  PTokenAnatomyRoute: PTokenAnatomyRoute,
  PTokenGroupRoute: PTokenGroupRoute,
  PTokenIntroRoute: PTokenIntroRoute,
  PTokenPendingRoute: PTokenPendingRoute,
  PTokenQuestionsRoute: PTokenQuestionsRoute,
  PTokenResultsRoute: PTokenResultsRoute,
  PTokenReviewRoute: PTokenReviewRoute,
  PTokenSetupRoute: PTokenSetupRoute,
  PTokenSummaryRoute: PTokenSummaryRoute,
  PTokenWaitingRoute: PTokenWaitingRoute,
}

const PTokenRouteRouteWithChildren = PTokenRouteRoute._addFileChildren(
  PTokenRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PTokenRouteRoute: PTokenRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
